version: '2'

services:
  admin_general_front:
    image: trion/ng-cli:12.2.8
    ports:
      - 4400:4200
    volumes:
     - ./:/app
    command: ["ng", "serve", "--host", "0.0.0.0", "--disable-host-check"]
